
CREATE DATABASE IF NOT EXISTS flaskdocker;
USE flaskdocker;

CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER IF NOT EXISTS 'flaskuser'@'%' IDENTIFIED BY '280903';
GRANT ALL PRIVILEGES ON flaskdocker.* TO 'flaskuser'@'%';
FLUSH PRIVILEGES;
