# version: '3.3'

services: 
  db:
    platform: linux/arm64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: douglas
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: douglas
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress 
volumes:
      db_data: {} 

